# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Random-walk Betweenness
#'
#' @param A (weighted) adjacency matrix
#' @return returns the random walk betweenness of each node
.rwbtw <- function(A) {
    .Call('_rwbtw_rwbtw', PACKAGE = 'rwbtw', A)
}

